<?php

namespace IndicoIo\Test;

use IndicoIo\IndicoIo as IndicoIo;
use PHPUnit\Framework\TestCase;

class KeywordsV2Test extends TestCase
{
    protected function setUp()
    {
        self::skipIfMissingCredentials();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function skipIfMissingCredentials()
    {
        if (!IndicoIo::$config['api_key']) {
            $this->markTestSkipped('No auth credentials provided, skipping batch tests...');
        }
    }

    /**
     * @test
     */
    public function testSingleKeywordsV2()
    {
        $text = "A working API is critical to the success of our company";
        $results = IndicoIo::keywords($text, array("version" => 2));
        $keywords = array_keys($results);
        foreach ($keywords as $keyword) {
            $this->assertTrue(strpos($text, $keyword) !== -1);
        }
    }

    /**
     * @test
     */
    public function testBatchKeywordsV2()
    {
        $text = "A working API is critical to the success of our company";
        $results = IndicoIo::keywords(array($text, $text), array("version" => 2));
        $this->assertEquals(count($results), 2);
        $keywords = array_keys($results[0]);

        foreach ($keywords as $keyword) {
            $this->assertTrue(strpos($text, $keyword) !== -1);
        }
    }

}
